### ISSUE TITLE
generate_patch.py not working correctly

### ISSUE THREAD

**Issue by FuseBarTV** [kinnay/NPLN-Protocols#19]
Hi There (again)

I've been having some issues with the generate_patch.py specifically having the error depicted in the picture here
![image](https://user-images.githubusercontent.com/70828143/227433643-77e87408-ec41-4429-8450-1b18520033cf.png)
Is this due to a Nintendo Switch image incompatibility or something similar?
Am I missing pip modules?
I'm quite lost...lol

Thanks!

**Comment by kinnay** [comment]
You should run it on the main nso, not the nsp. So, extract the exefs from the nsp and find a file called main. Then run `python3 generate_patch.py main`.

However, Splatoon 2 does not use NPLN so it will not work anyway.

**Comment by FuseBarTV** [comment]
Haha, I very much understand that Splat 2 uses NEX, I'm not completely stupid. Just didn't catch exactly how this file worked. With the amount of help you're giving, it makes me want to give you a big hug, but seriously thank you very much for your assistance.
